[package]
name = "BlakeHashing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.10.5"
hex = "0.4"
blake2-rfc = "0.2"